name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.NEW_PYPI_TOKEN }}
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.8"
#          cache-dependency-path: pyproject.toml
#      - uses: actions/cache@v3
#        id: cache
#        with:
#          path: ${{ env.pythonLocation }}
#          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish
#      - name: Install build dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: pip install build
#      - name: Build distribution
#        run: python -m build
#      - name: Publish
#        uses: pypa/gh-action-pypi-publish@v1.8.6
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
